
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  odl=ENV['ODL']
  config.ssh.insert_key= false
#  config.ssh.username = 'vagrant'
#  config.ssh.password = 'vagrant'
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
  end
  # run our bootstrapping for the system
  num_nodes = (ENV['NUM_NODES'] || 1).to_i

  # ip configuration
  ip_base = (ENV['SUBNET'] || "192.168.50.")
  ips = num_nodes.times.collect { |n| ip_base + "#{n+70}" }

  ip_base_intra = "192.168.53."
  ips_intra = num_nodes.times.collect { |n| ip_base_intra + "#{n+70}" }

  num_nodes.times do |n|
    config.vm.define "box#{n+1}", autostart: true do |compute|
      vm_ip = ips[n]
      vm_ip_intra = ips_intra[n]
      vm_index = n+1
#      compute.vm.box = "alagalah/gbpsfc-trusty64"
      compute.vm.box = "shidn/faas-sfc"
#      compute.vm.box_version = "1.0.1"
      compute.vm.hostname = "box#{vm_index}"
      compute.vm.network "private_network", ip: "#{vm_ip}"
      compute.vm.network "private_network", ip: "#{vm_ip_intra}"
      compute.vm.provider :virtualbox do |vb|
        vb.memory = 2048 
        vb.customize ["modifyvm", :id, "--ioapic", "on"]      
        vb.cpus = 1
      end
    end
  end
end
